### ISSUE TITLE
Fatal: Couldn't agree a key exchange algorithm

### ISSUE THREAD

**Issue by gnaghi** [kairyou/SublimeSimpleSync#11]
When syncing with a Ubuntu 20.04 server, the following error will happen : 

> Fatal: Couldn't agree a key exchange algorithm (available: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256)

This happens because the pscp software is too old : download the latest version here : https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html.

**Comment by kairyou** [comment]
Hello,
I've  added a [new version 1.0.15](https://packagecontrol.io/packages/SublimeSimpleSync) (update pscp to latest version). 

Thanks!
