### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by xiebaochun** [kairyou/SublimeSimpleSync#8]
I`m using it in ubuntu(linux), but it show a error dialog(which say '/bin/sh: 2: expect: not found') when after pressed  alt+s to upload file. The local & remote path are corrected.How to fixs this problem?

**Comment by kvtoraman** [comment]
Same problem...

**Comment by kairyou** [comment]
Sorry for late reply.
I have added the [FAQ section in README](https://github.com/kairyou/SublimeSimpleSync#faqs) for solve this issue.
