### ISSUE TITLE
Not Working in Ubuntu

### ISSUE THREAD

**Issue by jnrbo** [kairyou/SublimeSimpleSync#9]
Hi, I'm trying to use this on Ubuntu and is not working. I have two folders:

Local: **"~/dev/revenda/Revenda-Mais/"**
Mounted Local:  **"/mnt/testserver/"**

Both folders are accessible with cd.

My settings file:

```
{
  "config": {
    "autoSync": true,
    "debug": true,
    "timeout": 10
  },
  "rules": [
    {
      "type" : "local",
      "local" : "~/dev/revenda/Revenda-Mais/",
      "remote" :  "/mnt/testserver/"
    }
  ]
} 
```

Even with show console and debug true, nothing shows in console

Also im getting this warning, but i dont think is related:

> warning: mnemonic sss not found in menu caption Sublime Simple Sync

Thank you!

**Comment by kirillsimin** [comment]
I'm getting the same issue with `/home/username/...`

Getting the `msg: /bin/sh: 2: expect: not found` error.

Thanks.

**Comment by kvtoraman** [comment]
Same here, i also got `/bin/sh: 2: expect: not found`

**Comment by CooperNederhood** [comment]
I also get /bin/sh: 2: expect: not found

**Comment by kairyou** [comment]
Sorry for the wait.
The `expect` command is not installed on your system. 
Pls try run the following command in Terminal:
```sh
sudo apt-get update;
sudo apt-get install expect;
```
